#!/usr/bin/env sh
# . "$(dirname -- "$0")/_/husky.sh"

if [ "$SKIP_ALL" = "1" ]; then
    echo "⏭️  Skipping all checks"
    exit 0
fi

echo "🛂 Running lint..."
bun lint:all

echo "🧪 Running unit tests..."
bun test:unit

echo "🧩 Running component tests..."
bun test:component

if [ "$SKIP_E2E" = "1" ]; then
    echo "⏭️  Skipping E2E tests"
else
    echo "🌐 Running E2E tests..."
    bun test:e2e
fi
